In [1]:
import pandas as pd

In [2]:
d=pd.read_csv("Salary_Data.csv")
d

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
6699,49.0,Female,PhD,Director of Marketing,20.0,200000.0
6700,32.0,Male,High School,Sales Associate,3.0,50000.0
6701,30.0,Female,Bachelor's Degree,Financial Manager,4.0,55000.0
6702,46.0,Male,Master's Degree,Marketing Manager,14.0,140000.0
6703,26.0,Female,High School,Sales Executive,1.0,35000.0

In [3]:
d.columns

Index(['Age', 'Gender', 'Education Level', 'Job Title', 'Years of Experience',
       'Salary'],
      dtype='object')

In [4]:
d.columns[d.isnull().any()]

Index(['Age', 'Gender', 'Education Level', 'Job Title', 'Years of Experience',
       'Salary'],
      dtype='object')

In [5]:
d=d.drop(['Education Level'],axis=1)
d

       Age  Gender              Job Title  Years of Experience    Salary
0     32.0    Male      Software Engineer                  5.0   90000.0
1     28.0  Female           Data Analyst                  3.0   65000.0
2     45.0    Male         Senior Manager                 15.0  150000.0
3     36.0  Female        Sales Associate                  7.0   60000.0
4     52.0    Male               Director                 20.0  200000.0
...    ...     ...                    ...                  ...       ...
6699  49.0  Female  Director of Marketing                 20.0  200000.0
6700  32.0    Male        Sales Associate                  3.0   50000.0
6701  30.0  Female      Financial Manager                  4.0   55000.0
6702  46.0    Male      Marketing Manager                 14.0  140000.0
6703  26.0  Female        Sales Executive                  1.0   35000.0

[6704 rows x 5 columns]

In [6]:
d["Gender"].value_counts()

Gender
Male      3674
Female    3014
Other       14
Name: count, dtype: int64

In [8]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6704 entries, 0 to 6703
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  6702 non-null   float64
 1   Gender               6702 non-null   object
 2   Job Title            6702 non-null   object
 3   Years of Experience  6701 non-null   float64
 4   Salary               6699 non-null   float64
dtypes: float64(3), object(2)
memory usage: 262.0+ KB

In [9]:
e=pd.get_dummies(d["Gender"])
e

      Female   Male  Other
0      False   True  False
1       True  False  False
2      False   True  False
3       True  False  False
4      False   True  False
...      ...    ...    ...
6699    True  False  False
6700   False   True  False
6701    True  False  False
6702   False   True  False
6703    True  False  False

[6704 rows x 3 columns]

In [10]:
d=pd.concat([d,e],axis=1)
d

,Age,Gender,Job Title,Years of Experience,Salary,Female,Male,Other
0,32.0,Male,Software Engineer,5.0,90000.0,False,True,False
1,28.0,Female,Data Analyst,3.0,65000.0,True,False,False
2,45.0,Male,Senior Manager,15.0,150000.0,False,True,False
3,36.0,Female,Sales Associate,7.0,60000.0,True,False,False
4,52.0,Male,Director,20.0,200000.0,False,True,False
...,...,...,...,...,...,...,...,...
6699,49.0,Female,Director of Marketing,20.0,200000.0,True,False,False
6700,32.0,Male,Sales Associate,3.0,50000.0,False,True,False
6701,30.0,Female,Financial Manager,4.0,55000.0,True,False,False
6702,46.0,Male,Marketing Manager,14.0,140000.0,False,True,False
6703,26.0,Female,Sales Executive,1.0,35000.0,True,False,False

In [11]:
d["Years of Experience"] = d["Years of Experience"].fillna(d["Years of Experience"].mean())
d["Years of Experience"]

0        5.0
1        3.0
2       15.0
3        7.0
4       20.0
        ...
6699    20.0
6700     3.0
6701     4.0
6702    14.0
6703     1.0
Name: Years of Experience, Length: 6704, dtype: float64

In [13]:
d["Salary"] = d["Salary"].fillna(d["Salary"].mean())
d["Salary"]

0        90000.0
1        65000.0
2       150000.0
3        60000.0
4       200000.0
          ...
6699    200000.0
6700     50000.0
6701     55000.0
6702    140000.0
6703     35000.0
Name: Salary, Length: 6704, dtype: float64

In [17]:
from sklearn.model_selection import train_test_split

In [19]:
x=d[["Years of Experience"]]
y=d["Salary"]
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.7,random_state=42)
x_test

      Years of Experience
2794                 19.0
2233                  8.0
5559                  3.0
6355                  2.0
263                   3.0
...                   ...
2820                 32.0
3165                  8.0
5947                  0.0
6429                  3.0
2291                  2.0

[2012 rows x 1 columns]

In [20]:
from sklearn.linear_model import LinearRegression

In [21]:
from sklearn.metrics import r2_score

In [22]:
lr = LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [23]:
y_pred = lr.predict(x_test)
y_pred

array([192634.474479  , 114754.49957938,  79354.51098865, ...,
        58114.5178342 ,  79354.51098865,  72274.5132705 ], shape=(2012,))

In [24]:
lr.coef_

array([7079.99771815])

In [25]:
lr.intercept_

np.float64(58114.51783420499)

In [26]:
r2_score(y_test,y_pred)

0.6434486563267621

In [27]:
import numpy as np

In [29]:
a=np.array(4.7).reshape(-1,1)
b=lr.predict(a)
d

C:\Users\ASUS11\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

,Age,Gender,Job Title,Years of Experience,Salary,Female,Male,Other
0,32.0,Male,Software Engineer,5.0,90000.0,False,True,False
1,28.0,Female,Data Analyst,3.0,65000.0,True,False,False
2,45.0,Male,Senior Manager,15.0,150000.0,False,True,False
3,36.0,Female,Sales Associate,7.0,60000.0,True,False,False
4,52.0,Male,Director,20.0,200000.0,False,True,False
...,...,...,...,...,...,...,...,...
6699,49.0,Female,Director of Marketing,20.0,200000.0,True,False,False
6700,32.0,Male,Sales Associate,3.0,50000.0,False,True,False
6701,30.0,Female,Financial Manager,4.0,55000.0,True,False,False
6702,46.0,Male,Marketing Manager,14.0,140000.0,False,True,False
6703,26.0,Female,Sales Executive,1.0,35000.0,True,False,False